### ISSUE TITLE
Add support for Apple Silicon

### ISSUE THREAD

**Issue by mrsladek** [nais/wonderwall#67]
Could you think about adding QEMU into your GHA build script and build and push apple silicon images as well? 
Devs working on MBPs and running your software locally in docker would really appreciate it :) 

```
...
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
...
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          pull: true
...
```
